# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_accounts', '0002_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
