# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_accounts', '0003_auto_20160129_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.CharField(default='Not Created', max_length=255),
        ),
    ]
