# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_accounts', '0004_patient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='requested_doc',
            field=models.CharField(default='No Doctor Yet', max_length=255),
        ),
    ]
